In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import random as rd
from datetime import datetime, timedelta

import math

#  Matching Algorithm

In [3]:
now = datetime.now()
a = rd.randrange(60*17, 60*19, 5)
print(a)

hours = timedelta(minutes=a).seconds // 3600
minutes = (timedelta(minutes=a).seconds // 60) % 60
datetime(now.year, now.month, now.day, hour=hours, minute=minutes).strftime('%Y-%m-%d %H:%M:%S')

1070

'2023-03-08 17:50:00'

In [19]:
now = datetime.now()
num_user = 50

# 출발 희망 시각[변환 전]
start = [ rd.randrange(60*17, 60*19, 5) for i in range(num_user)]
# 출발 희망 시각[변환 후]
start_time = [ datetime(now.year, now.month, now.day, hour=timedelta(minutes=a).seconds // 3600, minute=(timedelta(minutes=a).seconds // 60) % 60).strftime('%Y-%m-%d %H:%M:%S') for a in start]

# 대기 가능 시간
wait = [ rd.randrange(10, 60,10) for i in range(num_user)]

# 최대 대기 시각[변환 전]
tolerance = [start[i] + wait[i] for i in range(num_user)]
# 최대 대기기 시각[변환 후]
tolerance_time = [ datetime(now.year, now.month, now.day, hour=timedelta(minutes=a).seconds // 3600, minute=(timedelta(minutes=a).seconds // 60) % 60).strftime('%Y-%m-%d %H:%M:%S') for a in tolerance]

# 우선순위
priority = [ i for i in range(1,num_user+1)]

# range_time
range_time = [(start[i], tolerance[i]) for i in range(num_user)]

# ID
ID = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','BB','CC','DD','EE','FF','GG','HH','II','JJ','KK','LL','MM','NN','OO','PP','QQ','RR','SS','TT','UU','VV','WW','XX','YY','ZZ']
id = ID[:num_user]

# 출발지 lat(위도)&lon(경도) [0,1000 사이의 난수] '도'가 아니라 가시를 위해 '초'로 표시하였다.
start_lat = [round(1000*rd.random(),4) for i in range(num_user)]
start_lon = [round(1000*rd.random(),4) for i in range(num_user)]
start_loc = [(start_lat[i], start_lon[i]) for i in range(num_user)]

# 출발지 lat(위도)&lon(경도) [0,1000 사이의 난수]
des_lat = [round(1000*rd.random(),4) for i in range(num_user)]
des_lon = [round(1000*rd.random(),4) for i in range(num_user)]
des_loc = [(des_lat[i], des_lon[i]) for i in range(num_user)]

Step1

Step2  $A$의 출발지와 목적지를 직선으로 이은 벡터를 $v_A$라고 하고, 그 외의 $i$의 출발지와 목적지를 직선으로 이은 벡터를 $v_i$라고 하자

In [20]:
df1 = pd.DataFrame(dict(zip(['ID','출발희망시각','최대대기시각','우선순위','시간범위','출발위치','도착위치'],[id, start_time, tolerance_time, priority, range_time, start_loc, des_loc])))
df1 = df1.sort_values(by=['출발희망시각','최대대기시각']) # sorting
df1 = df1.set_index('우선순위')
df1

,ID,출발희망시각,최대대기시각,시간범위,출발위치,도착위치
우선순위,,,,,,
48,VV,2023-03-08 17:00:00,2023-03-08 17:10:00,"(1020, 1030)","(455.711, 806.4569)","(899.698, 308.4021)"
40,NN,2023-03-08 17:20:00,2023-03-08 17:30:00,"(1040, 1050)","(698.9117, 329.3483)","(994.9829, 798.8509)"
25,Y,2023-03-08 17:20:00,2023-03-08 18:00:00,"(1040, 1080)","(749.8871, 410.8121)","(103.5077, 765.9093)"
3,C,2023-03-08 17:20:00,2023-03-08 18:10:00,"(1040, 1090)","(953.3646, 994.9811)","(519.6023, 938.949)"
23,W,2023-03-08 17:20:00,2023-03-08 18:10:00,"(1040, 1090)","(252.0992, 690.7801)","(179.5668, 369.1665)"
44,RR,2023-03-08 17:25:00,2023-03-08 17:35:00,"(1045, 1055)","(435.9572, 160.815)","(597.1445, 341.2754)"
30,DD,2023-03-08 17:30:00,2023-03-08 17:40:00,"(1050, 1060)","(958.9424, 333.8555)","(637.0216, 182.4454)"
50,XX,2023-03-08 17:30:00,2023-03-08 17:40:00,"(1050, 1060)","(792.2967, 698.2721)","(645.0259, 899.2306)"
31,EE,2023-03-08 17:30:00,2023-03-08 18:10:00,"(1050, 1090)","(766.0019, 577.3276)","(718.994, 821.5069)"
42,PP,2023-03-08 17:35:00,2023-03-08 17:45:00,"(1055, 1065)","(354.0012, 15.8651)","(430.9149, 132.7621)"
16,P,2023-03-08 17:35:00,2023-03-08 17:55:00,"(1055, 1075)","(884.1501, 212.9487)","(751.1265, 315.3682)"
27,AA,2023-03-08 17:35:00,2023-03-08 17:55:00,"(1055, 1075)","(949.8076, 327.8583)","(5.0736, 402.8762)"
2,B,2023-03-08 17:40:00,2023-03-08 17:50:00,"(1060, 1070)","(59.1823, 266.6844)","(319.9904, 963.1359)"
6,F,2023-03-08 17:40:00,2023-03-08 17:50:00,"(1060, 1070)","(471.9561, 297.7539)","(770.52, 669.4682)"
35,II,2023-03-08 17:40:00,2023-03-08 18:00:00,"(1060, 1080)","(664.2314, 651.1343)","(102.3356, 421.5122)"
36,JJ,2023-03-08 17:40:00,2023-03-08 18:10:00,"(1060, 1090)","(639.9166, 557.267)","(586.6614, 909.6197)"
28,BB,2023-03-08 17:45:00,2023-03-08 18:15:00,"(1065, 1095)","(454.6596, 592.869)","(28.8711, 845.8005)"
14,N,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(208.4491, 950.4344)","(4.1927, 968.4496)"
43,QQ,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(135.0804, 576.8754)","(395.1004, 561.7569)"
49,WW,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(676.0437, 480.7869)","(772.1581, 450.7657)"
39,MM,2023-03-08 17:45:00,2023-03-08 18:35:00,"(1065, 1115)","(835.7121, 713.9601)","(817.8797, 749.2103)"
34,HH,2023-03-08 17:50:00,2023-03-08 18:00:00,"(1070, 1080)","(563.7017, 462.2907)","(454.2152, 157.547)"
1,A,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(484.3424, 10.1435)","(891.9075, 499.3931)"
10,J,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(397.0949, 168.8192)","(685.3074, 142.0656)"
37,KK,2023-03-08 17:55:00,2023-03-08 18:45:00,"(1075, 1125)","(0.0153, 69.9949)","(262.316, 290.3581)"
9,I,2023-03-08 18:00:00,2023-03-08 18:10:00,"(1080, 1090)","(594.1945, 852.6876)","(734.1846, 407.4984)"
15,O,2023-03-08 18:00:00,2023-03-08 18:10:00,"(1080, 1090)","(94.0329, 982.4495)","(421.53, 756.9472)"
5,E,2023-03-08 18:00:00,2023-03-08 18:20:00,"(1080, 1100)","(259.2649, 133.5038)","(789.0382, 264.8621)"
38,LL,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(673.496, 57.0232)","(421.2215, 903.9945)"
46,TT,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(719.1732, 883.2421)","(80.3009, 712.4014)"
20,T,2023-03-08 18:15:00,2023-03-08 18:45:00,"(1095, 1125)","(534.3056, 81.8538)","(906.2157, 530.7436)"
47,UU,2023-03-08 18:20:00,2023-03-08 18:30:00,"(1100, 1110)","(667.2399, 390.6792)","(37.1933, 890.0685)"
45,SS,2023-03-08 18:20:00,2023-03-08 18:40:00,"(1100, 1120)","(774.1433, 397.5184)","(930.7401, 537.1504)"
11,K,2023-03-08 18:20:00,2023-03-08 19:00:00,"(1100, 1140)","(547.6131, 506.4008)","(149.097, 837.6343)"
26,Z,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(578.2449, 332.8943)","(321.3845, 242.2946)"
32,FF,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(362.5892, 408.05)","(943.3087, 355.7375)"
12,L,2023-03-08 18:25:00,2023-03-08 18:45:00,"(1105, 1125)","(969.2777, 578.2054)","(649.31, 813.8624)"
29,CC,2023-03-08 18:25:00,2023-03-08 18:55:00,"(1105, 1135)","(527.6682, 762.2756)","(312.6771, 947.6548)"
8,H,2023-03-08 18:25:00,2023-03-08 19:15:00,"(1105, 1155)","(153.4537, 394.5352)","(222.3449, 613.5783)"
17,Q,2023-03-08 18:30:00,2023-03-08 18:40:00,"(1110, 1120)","(970.9059, 644.9593)","(400.4372, 493.6852)"
19,S,2023-03-08 18:30:00,2023-03-08 19:00:00,"(1110, 1140)","(410.2889, 464.0945)","(944.2342, 282.0157)"
33,GG,2023-03-08 18:30:00,2023-03-08 19:10:00,"(1110, 1150)","(690.6333, 795.2414)","(445.1676, 59.2849)"
21,U,2023-03-08 18:35:00,2023-03-08 18:45:00,"(1115, 1125)","(11.7673, 628.7937)","(108.0999, 630.8992)"
41,OO,2023-03-08 18:35:00,2023-03-08 18:45:00,"(1115, 1125)","(11.0211, 834.5347)","(69.8057, 504.2777)"
13,M,2023-03-08 18:40:00,2023-03-08 19:10:00,"(1120, 1150)","(567.6657, 318.0315)","(775.812, 364.2509)"
24,X,2023-03-08 18:45:00,2023-03-08 19:15:00,"(1125, 1155)","(889.0922, 551.4916)","(990.414, 951.6513)"
4,D,2023-03-08 18:50:00,2023-03-08 19:30:00,"(1130, 1170)","(161.6841, 886.7748)","(82.4108, 717.1546)"
18,R,2023-03-08 18:50:00,2023-03-08 19:30:00,"(1130, 1170)","(540.8494, 558.8615)","(668.0212, 45.9912)"
7,G,2023-03-08 18:50:00,2023-03-08 19:40:00,"(1130, 1180)","(527.5811, 214.3994)","(891.4053, 112.0633)"
22,V,2023-03-08 18:55:00,2023-03-08 19:45:00,"(1135, 1185)","(53.0317, 914.5662)","(442.374, 609.0252)"

Step3. 1순위($A$)의 출발희망시각과 최대 대기 시각과 겹치지 않는 ID는 탈락한다.

In [21]:
start, end = df1.loc[1]['시간범위']
for index, row in df1.iterrows():
  st, en = df1.loc[index]['시간범위']
  if start>=en or end<=st:
    df1 = df1.drop(index, axis=0)

Step4. $A$의 출발지&도착지 기준 반경 $m$km 이내에 벡터가 겹치는 ID만 남긴다

In [22]:
# A의 위치정보
start_lat, start_lon = df1.loc[1]['출발위치']
end_lat, end_lon = df1.loc[1]['도착위치']

m = 20 # 20초
m = m*1000/37 # km를 초로 치환, 1초는 37m이다

# 직선의 방정식
def line_eq(x1, y1, x2, y2):
  m = (y2 - y1) / (x2 - x1)
  b = y1 - m * x1
  A, B, C = -m, 1, -b
  return A, B, C

# 직선과 A 사이의 거리
def distance(x1, y1, a, b, c):
  dist = abs(a*x1 + b*y1 + c) / math.sqrt(a*a + b*b)
  return dist

for index, row in df1.iterrows():
  st_lat, st_lon = df1.loc[index]['출발위치']
  en_lat, en_lon = df1.loc[index]['도착위치']

  # 각 ID의 벡터
  a, b, c = line_eq(st_lat, st_lon, en_lat, en_lon)
  # 각 ID의 벡터와 A 출발점 사이의 거리
  dist_from_st = distance(start_lat, start_lon, a, b, c)
  # 각 ID의 벡터와 B 출발점 사이의 거리
  dist_from_en = distance(end_lat, end_lon, a, b, c)

  # print(dist_from_st, dist_from_en)
  
  if dist_from_st >= m and dist_from_en >= m:
    df1 = df1.drop(index, axis=0)

df1

,ID,출발희망시각,최대대기시각,시간범위,출발위치,도착위치
우선순위,,,,,,
25,Y,2023-03-08 17:20:00,2023-03-08 18:00:00,"(1040, 1080)","(749.8871, 410.8121)","(103.5077, 765.9093)"
3,C,2023-03-08 17:20:00,2023-03-08 18:10:00,"(1040, 1090)","(953.3646, 994.9811)","(519.6023, 938.949)"
23,W,2023-03-08 17:20:00,2023-03-08 18:10:00,"(1040, 1090)","(252.0992, 690.7801)","(179.5668, 369.1665)"
31,EE,2023-03-08 17:30:00,2023-03-08 18:10:00,"(1050, 1090)","(766.0019, 577.3276)","(718.994, 821.5069)"
16,P,2023-03-08 17:35:00,2023-03-08 17:55:00,"(1055, 1075)","(884.1501, 212.9487)","(751.1265, 315.3682)"
27,AA,2023-03-08 17:35:00,2023-03-08 17:55:00,"(1055, 1075)","(949.8076, 327.8583)","(5.0736, 402.8762)"
35,II,2023-03-08 17:40:00,2023-03-08 18:00:00,"(1060, 1080)","(664.2314, 651.1343)","(102.3356, 421.5122)"
36,JJ,2023-03-08 17:40:00,2023-03-08 18:10:00,"(1060, 1090)","(639.9166, 557.267)","(586.6614, 909.6197)"
28,BB,2023-03-08 17:45:00,2023-03-08 18:15:00,"(1065, 1095)","(454.6596, 592.869)","(28.8711, 845.8005)"
14,N,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(208.4491, 950.4344)","(4.1927, 968.4496)"
43,QQ,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(135.0804, 576.8754)","(395.1004, 561.7569)"
49,WW,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(676.0437, 480.7869)","(772.1581, 450.7657)"
39,MM,2023-03-08 17:45:00,2023-03-08 18:35:00,"(1065, 1115)","(835.7121, 713.9601)","(817.8797, 749.2103)"
34,HH,2023-03-08 17:50:00,2023-03-08 18:00:00,"(1070, 1080)","(563.7017, 462.2907)","(454.2152, 157.547)"
1,A,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(484.3424, 10.1435)","(891.9075, 499.3931)"
10,J,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(397.0949, 168.8192)","(685.3074, 142.0656)"
37,KK,2023-03-08 17:55:00,2023-03-08 18:45:00,"(1075, 1125)","(0.0153, 69.9949)","(262.316, 290.3581)"
9,I,2023-03-08 18:00:00,2023-03-08 18:10:00,"(1080, 1090)","(594.1945, 852.6876)","(734.1846, 407.4984)"
15,O,2023-03-08 18:00:00,2023-03-08 18:10:00,"(1080, 1090)","(94.0329, 982.4495)","(421.53, 756.9472)"
5,E,2023-03-08 18:00:00,2023-03-08 18:20:00,"(1080, 1100)","(259.2649, 133.5038)","(789.0382, 264.8621)"
38,LL,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(673.496, 57.0232)","(421.2215, 903.9945)"
46,TT,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(719.1732, 883.2421)","(80.3009, 712.4014)"
20,T,2023-03-08 18:15:00,2023-03-08 18:45:00,"(1095, 1125)","(534.3056, 81.8538)","(906.2157, 530.7436)"
47,UU,2023-03-08 18:20:00,2023-03-08 18:30:00,"(1100, 1110)","(667.2399, 390.6792)","(37.1933, 890.0685)"
45,SS,2023-03-08 18:20:00,2023-03-08 18:40:00,"(1100, 1120)","(774.1433, 397.5184)","(930.7401, 537.1504)"
11,K,2023-03-08 18:20:00,2023-03-08 19:00:00,"(1100, 1140)","(547.6131, 506.4008)","(149.097, 837.6343)"
26,Z,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(578.2449, 332.8943)","(321.3845, 242.2946)"
32,FF,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(362.5892, 408.05)","(943.3087, 355.7375)"
12,L,2023-03-08 18:25:00,2023-03-08 18:45:00,"(1105, 1125)","(969.2777, 578.2054)","(649.31, 813.8624)"
29,CC,2023-03-08 18:25:00,2023-03-08 18:55:00,"(1105, 1135)","(527.6682, 762.2756)","(312.6771, 947.6548)"
8,H,2023-03-08 18:25:00,2023-03-08 19:15:00,"(1105, 1155)","(153.4537, 394.5352)","(222.3449, 613.5783)"

In [23]:
# m = 10
for index, row in df1.iterrows():
  st_lat, st_lon = df1.loc[index]['출발위치']
  en_lat, en_lon = df1.loc[index]['도착위치']
  a, b, c = line_eq(st_lat, st_lon, en_lat, en_lon)
  dist_from_st = distance(start_lat, start_lon, a, b, c)
  dist_from_en = distance(end_lat, end_lon, a, b, c)
  print(min(dist_from_st, dist_from_en))

146.01839195987085
483.63075390762816
376.29392357942504
108.90243918720918
231.69794612584172
166.4133385130436
226.59213089951643
235.59168445769242
142.9442630978607
389.24992152960664
33.421199042711805
82.11836677928355
46.71280077667596
78.1921292873883
0.0
149.93229557089882
244.93133722459788
178.02519498408228
54.63184525185766
173.9026472293389
194.66530475588954
415.44255989291577
7.276586215396036
224.7523241229169
2.337362377129519
214.6840349935094
52.682733154590025
138.4645944377343
109.34080732113537
38.76664936743312
430.9711357140837

Step5. 벡터 연산을 통해 구한 사이각과 스칼라값을 통해 조건을 만족하지 않는 ID는 탈락한다.

In [24]:
# A의 위치정보
start_lat, start_lon = df1.loc[1]['출발위치']
end_lat, end_lon = df1.loc[1]['도착위치']

a_vec = [start_lat-end_lat, start_lon-end_lon]
print(a_vec)
for index, row in df1.iterrows():
  st_lat, st_lon = df1.loc[index]['출발위치']
  en_lat, en_lon = df1.loc[index]['도착위치']
  i_vec = [st_lat-en_lat, st_lon-en_lon]

  if max(math.sqrt(a_vec[0]**2 + a_vec[1]**2),math.sqrt(i_vec[0]**2 + i_vec[1]**2)) < math.sqrt((a_vec[0]-i_vec[0])**2+(a_vec[1]-i_vec[1])**2):
    df1 = df1.drop(index, axis=0)

df2 = df1.copy()
df1

[-407.56510000000003, -489.2496]

,ID,출발희망시각,최대대기시각,시간범위,출발위치,도착위치
우선순위,,,,,,
31,EE,2023-03-08 17:30:00,2023-03-08 18:10:00,"(1050, 1090)","(766.0019, 577.3276)","(718.994, 821.5069)"
36,JJ,2023-03-08 17:40:00,2023-03-08 18:10:00,"(1060, 1090)","(639.9166, 557.267)","(586.6614, 909.6197)"
43,QQ,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(135.0804, 576.8754)","(395.1004, 561.7569)"
49,WW,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(676.0437, 480.7869)","(772.1581, 450.7657)"
39,MM,2023-03-08 17:45:00,2023-03-08 18:35:00,"(1065, 1115)","(835.7121, 713.9601)","(817.8797, 749.2103)"
1,A,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(484.3424, 10.1435)","(891.9075, 499.3931)"
10,J,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(397.0949, 168.8192)","(685.3074, 142.0656)"
37,KK,2023-03-08 17:55:00,2023-03-08 18:45:00,"(1075, 1125)","(0.0153, 69.9949)","(262.316, 290.3581)"
5,E,2023-03-08 18:00:00,2023-03-08 18:20:00,"(1080, 1100)","(259.2649, 133.5038)","(789.0382, 264.8621)"
38,LL,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(673.496, 57.0232)","(421.2215, 903.9945)"
20,T,2023-03-08 18:15:00,2023-03-08 18:45:00,"(1095, 1125)","(534.3056, 81.8538)","(906.2157, 530.7436)"
45,SS,2023-03-08 18:20:00,2023-03-08 18:40:00,"(1100, 1120)","(774.1433, 397.5184)","(930.7401, 537.1504)"
32,FF,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(362.5892, 408.05)","(943.3087, 355.7375)"
8,H,2023-03-08 18:25:00,2023-03-08 19:15:00,"(1105, 1155)","(153.4537, 394.5352)","(222.3449, 613.5783)"

In [25]:
for index, row in df1.iterrows():
  st_lat, st_lon = df1.loc[index]['출발위치']
  en_lat, en_lon = df1.loc[index]['도착위치']
  i_vec = [st_lat-en_lat, st_lon-en_lon]
  print(i_vec)

[47.00789999999995, -244.1793]
[53.25520000000006, -352.3526999999999]
[-260.02, 15.11850000000004]
[-96.11440000000005, 30.02120000000002]
[17.832400000000007, -35.25019999999995]
[-407.56510000000003, -489.2496]
[-288.21250000000003, 26.753600000000006]
[-262.30069999999995, -220.36319999999998]
[-529.7733, -131.35829999999999]
[252.2745, -846.9713]
[-371.91009999999994, -448.88980000000004]
[-156.59680000000003, -139.632]
[-580.7195, 52.3125]
[-68.8912, -219.04310000000004]

Step6. (추후 개발)

Step7. $A$와 선정된 후보들을 경유했을 때의 실제 경로의 운행 시간과 비용을 바탕으로 최적의 경유지를 탐색한다

In [26]:
start_lat, start_lon = df1.loc[1]['출발위치']
end_lat, end_lon = df1.loc[1]['도착위치']

df1 = df1.drop(1, axis=0)
df1

,ID,출발희망시각,최대대기시각,시간범위,출발위치,도착위치
우선순위,,,,,,
31,EE,2023-03-08 17:30:00,2023-03-08 18:10:00,"(1050, 1090)","(766.0019, 577.3276)","(718.994, 821.5069)"
36,JJ,2023-03-08 17:40:00,2023-03-08 18:10:00,"(1060, 1090)","(639.9166, 557.267)","(586.6614, 909.6197)"
43,QQ,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(135.0804, 576.8754)","(395.1004, 561.7569)"
49,WW,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(676.0437, 480.7869)","(772.1581, 450.7657)"
39,MM,2023-03-08 17:45:00,2023-03-08 18:35:00,"(1065, 1115)","(835.7121, 713.9601)","(817.8797, 749.2103)"
10,J,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(397.0949, 168.8192)","(685.3074, 142.0656)"
37,KK,2023-03-08 17:55:00,2023-03-08 18:45:00,"(1075, 1125)","(0.0153, 69.9949)","(262.316, 290.3581)"
5,E,2023-03-08 18:00:00,2023-03-08 18:20:00,"(1080, 1100)","(259.2649, 133.5038)","(789.0382, 264.8621)"
38,LL,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(673.496, 57.0232)","(421.2215, 903.9945)"
20,T,2023-03-08 18:15:00,2023-03-08 18:45:00,"(1095, 1125)","(534.3056, 81.8538)","(906.2157, 530.7436)"
45,SS,2023-03-08 18:20:00,2023-03-08 18:40:00,"(1100, 1120)","(774.1433, 397.5184)","(930.7401, 537.1504)"
32,FF,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(362.5892, 408.05)","(943.3087, 355.7375)"
8,H,2023-03-08 18:25:00,2023-03-08 19:15:00,"(1105, 1155)","(153.4537, 394.5352)","(222.3449, 613.5783)"

In [27]:
df3 = df1.copy()
epoch = 4
'''
우선 x좌표를 기준으로 sorting하여 경유지를 설정하였다. 추후 경유지API 가져와 변경 예정
[2021년 서울 차량 통행속도 분석]에 따르면 지난해 도심 통행속도는 시속 23㎞'라는 정보를 활용해 시간을 산출하였다.
1초 사이의 거리는 0.037 km = 37 m 이므로 이를 기반으로 거리를 산출하였다.
'''

def distance(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1
    dist = math.sqrt(dx*dx + dy*dy)
    return dist

for index, row in df1.iterrows():
  st_lat, st_lon = df1.loc[index]['출발위치']
  en_lat, en_lon = df1.loc[index]['도착위치']
  lat_lon = {
      start_lat: start_lon,
      end_lat: end_lon,
      st_lat: st_lon,
      en_lat: en_lon
      }
  # 원점에서 떨어진 거리순으로 정렬
  dis_lat = {
      distance(0, 0, start_lat, start_lon): start_lat, # a 시작지점
      distance(0, 0, end_lat,end_lon): end_lat, # a 끝지점
      distance(0, 0, st_lat, st_lon): st_lat, # i 시작지점
      distance(0, 0, en_lat, en_lon): en_lat # i 끝지점
      }


  dis = sorted([distance(0, 0, start_lat, start_lon), distance(0, 0, end_lat,end_lon), distance(0, 0, st_lat, st_lon), distance(0, 0, en_lat, en_lon)])

  routing_lat = [ dis_lat[key] for key in dis]
  routing_lon = [ lat_lon[key] for key in routing_lat]

  print('routing_lat: ',routing_lat)
  print('routing_lon: ',routing_lon)
  print(f'A start: {start_lat, start_lon} A end: {end_lat, end_lon}')
  print(f'I start: {st_lat, st_lon} I end: {en_lat, en_lon}')

  # 경유 node
  if routing_lat.index(start_lat) > routing_lat.index(end_lat) or routing_lat.index(st_lat) > routing_lat.index(en_lat):
    routing_lat = routing_lat[::-1]
    routing_lon = routing_lon[::-1]
    a_routing_idx = [routing_lat.index(start_lat), routing_lat.index(end_lat)]
    i_routing_idx = [routing_lat.index(st_lat), routing_lat.index(en_lat)]

  else:
    a_routing_idx = [routing_lat.index(start_lat), routing_lat.index(end_lat)]
    i_routing_idx = [routing_lat.index(st_lat), routing_lat.index(en_lat)]
  

  a_route_dist = 0
  a_dist = 0
  start_point = a_routing_idx[0]
  end_point = a_routing_idx[1]
  print(start_point<end_point)

  
  # 0>1 , 2>3 인 경우 제외
  if (start_point, end_point) == (0,1) or (start_point, end_point) == (2,3):
    df1 = df1.drop(index, axis=0)
    print('wrong match')
    print()

  else:
    print(start_point, end_point)

    # 타킷경유시간(분)
    point = start_point
    try:
      for i in range(epoch):
        # a가 노드
        x1 = routing_lat[point]
        y1 = routing_lon[point]
        # 다음 노드
        point += 1

        x2 = routing_lat[point]
        y2 = routing_lon[point]
        dist_btn_node = distance(x1, y1, x2, y2) * 0.037 # 초(각도) >> km(거리)
        a_route_dist += dist_btn_node
        if point==end_point:
          break
    except:
      pass

    a_route_time = 60/23 * a_route_dist # km(거리) >> 분(시간)
    df1.loc[index,'타깃경유시간(분)'] = a_route_time
    df1.loc[index,'타깃경유거리(km)'] = a_route_dist

    # 타킷원래시간(분)
    # a 출발
    x1 = routing_lat[start_point]
    y1 = routing_lon[start_point]
    # a 도착
    x2 = routing_lat[end_point]
    y2 = routing_lon[end_point]
    a_dist = distance(x1, y1, x2, y2) * 0.037
    a_time = 60/23 * a_dist
    df1.loc[index,'타깃원래시간(분)'] = a_time
    df1.loc[index,'타깃원래거리(km)'] = a_dist


    i_route_dist = 0
    i_dist = 0
    start_point = i_routing_idx[0]
    end_point = i_routing_idx[1]
    print(start_point, end_point)

    # 경유시간(분)
    point = start_point
    try:
      for i in range(epoch):
        # a가 노드
        x1 = routing_lat[point]
        y1 = routing_lon[point]
        # 다음 노드
        point += 1
        x2 = routing_lat[point]
        y2 = routing_lon[point]
        dist_btn_node = distance(x1, y1, x2, y2) * 0.037 # 초(각도) >> km(거리)
        i_route_dist += dist_btn_node
        if point==end_point:
          break
    except:
      pass

    i_route_time = 60/23 * i_route_dist # km(거리) >> 분(시간)
    df1.loc[index,'경유시간(분)'] = i_route_time
    df1.loc[index,'경유거리(km)'] = i_route_dist

    # 원래시간(분)
    # i 출발
    x1 = routing_lat[start_point]
    y1 = routing_lon[start_point]
    # i 도착
    x2 = routing_lat[end_point]
    y2 = routing_lon[end_point]
    i_dist = distance(x1, y1, x2, y2) * 0.037
    i_time = 60/23 * i_dist
    df1.loc[index,'원래시간(분)'] = i_time
    df1.loc[index,'원래거리(km)'] = i_dist

    print(routing_lat, routing_lon)
    print()


    total_route_dist = 0
    point = 0

    # 전체체경유시간(분)
    try:
      for i in range(epoch):
        # a가 노드
        x1 = routing_lat[point]
        y1 = routing_lon[point]
        # 다음 노드
        point += 1

        x2 = routing_lat[point]
        y2 = routing_lon[point]
        dist_btn_node = distance(x1, y1, x2, y2) * 0.037 # 초(각도) >> km(거리)
        total_route_dist += dist_btn_node
        if point==4:
          break
    except:
      pass

    total_time = 60/23 * total_route_dist
    df1.loc[index,'총이동시간(분)'] = total_time
    df1.loc[index,'총경유거리(km)'] = total_route_dist

df1

routing_lat:  [484.3424, 766.0019, 891.9075, 718.994]
routing_lon:  [10.1435, 577.3276, 499.3931, 821.5069]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (766.0019, 577.3276) I end: (718.994, 821.5069)
True
0 2
1 3
[484.3424, 766.0019, 891.9075, 718.994] [10.1435, 577.3276, 499.3931, 821.5069]

routing_lat:  [484.3424, 639.9166, 891.9075, 586.6614]
routing_lon:  [10.1435, 557.267, 499.3931, 909.6197]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (639.9166, 557.267) I end: (586.6614, 909.6197)
True
0 2
1 3
[484.3424, 639.9166, 891.9075, 586.6614] [10.1435, 557.267, 499.3931, 909.6197]

routing_lat:  [484.3424, 135.0804, 395.1004, 891.9075]
routing_lon:  [10.1435, 576.8754, 561.7569, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (135.0804, 576.8754) I end: (395.1004, 561.7569)
True
0 3
1 2
[484.3424, 135.0804, 395.1004, 891.9075] [10.1435, 576.8754, 561.7569, 499.3931]

routing_lat:  [484.3424, 676.0437, 772.1581, 891.9075]
routing_lon:  [10.1435, 480.7869, 450.7657, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (676.0437, 480.7869) I end: (772.1581, 450.7657)
True
0 3
1 2
[484.3424, 676.0437, 772.1581, 891.9075] [10.1435, 480.7869, 450.7657, 499.3931]

routing_lat:  [484.3424, 891.9075, 835.7121, 817.8797]
routing_lon:  [10.1435, 499.3931, 713.9601, 749.2103]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (835.7121, 713.9601) I end: (817.8797, 749.2103)
True
wrong match

routing_lat:  [397.0949, 484.3424, 685.3074, 891.9075]
routing_lon:  [168.8192, 10.1435, 142.0656, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (397.0949, 168.8192) I end: (685.3074, 142.0656)
True
1 3
0 2
[397.0949, 484.3424, 685.3074, 891.9075] [168.8192, 10.1435, 142.0656, 499.3931]

routing_lat:  [0.0153, 262.316, 484.3424, 891.9075]
routing_lon:  [69.9949, 290.3581, 10.1435, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (0.0153, 69.9949) I end: (262.316, 290.3581)
True
wrong match

routing_lat:  [259.2649, 484.3424, 789.0382, 891.9075]
routing_lon:  [133.5038, 10.1435, 264.8621, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (259.2649, 133.5038) I end: (789.0382, 264.8621)
True
1 3
0 2
[259.2649, 484.3424, 789.0382, 891.9075] [133.5038, 10.1435, 264.8621, 499.3931]

routing_lat:  [484.3424, 673.496, 421.2215, 891.9075]
routing_lon:  [10.1435, 57.0232, 903.9945, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (673.496, 57.0232) I end: (421.2215, 903.9945)
True
0 3
1 2
[484.3424, 673.496, 421.2215, 891.9075] [10.1435, 57.0232, 903.9945, 499.3931]

routing_lat:  [484.3424, 534.3056, 891.9075, 906.2157]
routing_lon:  [10.1435, 81.8538, 499.3931, 530.7436]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (534.3056, 81.8538) I end: (906.2157, 530.7436)
True
0 2
1 3
[484.3424, 534.3056, 891.9075, 906.2157] [10.1435, 81.8538, 499.3931, 530.7436]

routing_lat:  [484.3424, 774.1433, 891.9075, 930.7401]
routing_lon:  [10.1435, 397.5184, 499.3931, 537.1504]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (774.1433, 397.5184) I end: (930.7401, 537.1504)
True
0 2
1 3
[484.3424, 774.1433, 891.9075, 930.7401] [10.1435, 397.5184, 499.3931, 537.1504]

routing_lat:  [484.3424, 362.5892, 943.3087, 891.9075]
routing_lon:  [10.1435, 408.05, 355.7375, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (362.5892, 408.05) I end: (943.3087, 355.7375)
True
0 3
1 2
[484.3424, 362.5892, 943.3087, 891.9075] [10.1435, 408.05, 355.7375, 499.3931]

routing_lat:  [153.4537, 484.3424, 222.3449, 891.9075]
routing_lon:  [394.5352, 10.1435, 613.5783, 499.3931]
A start: (484.3424, 10.1435) A end: (891.9075, 499.3931)
I start: (153.4537, 394.5352) I end: (222.3449, 613.5783)
True
1 3
0 2
[153.4537, 484.3424, 222.3449, 891.9075] [394.5352, 10.1435, 613.5783, 499.3931]

,ID,출발희망시각,최대대기시각,시간범위,출발위치,도착위치,타깃경유시간(분),타깃경유거리(km),타깃원래시간(분),타깃원래거리(km),경유시간(분),경유거리(km),원래시간(분),원래거리(km),총이동시간(분),총경유거리(km)
우선순위,,,,,,,,,,,,,,,,
31,EE,2023-03-08 17:30:00,2023-03-08 18:10:00,"(1050, 1090)","(766.0019, 577.3276)","(718.994, 821.5069)",75.416636,28.909710,61.46203,23.560445,49.579818,19.005597,24.001382,9.200530,110.704062,42.436557
36,JJ,2023-03-08 17:40:00,2023-03-08 18:10:00,"(1060, 1090)","(639.9166, 557.267)","(586.6614, 909.6197)",79.858581,30.612456,61.46203,23.560445,74.310540,28.485707,34.395958,13.185117,129.213294,49.531763
43,QQ,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(135.0804, 576.8754)","(395.1004, 561.7569)",137.724416,52.794359,61.46203,23.560445,25.139970,9.636989,25.139970,9.636989,137.724416,52.794359
49,WW,2023-03-08 17:45:00,2023-03-08 18:25:00,"(1065, 1105)","(676.0437, 480.7869)","(772.1581, 450.7657)",71.245346,27.310716,61.46203,23.560445,9.719145,3.725672,9.719145,3.725672,71.245346,27.310716
10,J,2023-03-08 17:50:00,2023-03-08 18:30:00,"(1070, 1110)","(397.0949, 168.8192)","(685.3074, 142.0656)",63.043280,24.166591,61.46203,23.560445,40.681660,15.594636,27.938367,10.709707,80.521474,30.866565
5,E,2023-03-08 18:00:00,2023-03-08 18:20:00,"(1080, 1100)","(259.2649, 133.5038)","(789.0382, 264.8621)",63.051911,24.169899,61.46203,23.560445,63.106643,24.190880,52.683078,20.195180,87.825799,33.666556
38,LL,2023-03-08 18:10:00,2023-03-08 18:50:00,"(1090, 1130)","(673.496, 57.0232)","(421.2215, 903.9945)",164.019696,62.874217,61.46203,23.560445,85.300472,32.698514,85.300472,32.698514,164.019696,62.874217
20,T,2023-03-08 18:15:00,2023-03-08 18:45:00,"(1095, 1125)","(534.3056, 81.8538)","(906.2157, 530.7436)",61.498183,23.574303,61.46203,23.560445,56.388483,21.615585,56.266393,21.568784,64.824444,24.849370
45,SS,2023-03-08 18:20:00,2023-03-08 18:40:00,"(1100, 1120)","(774.1433, 397.5184)","(930.7401, 537.1504)",61.725155,23.661309,61.46203,23.560445,20.257656,7.765435,20.251092,7.762919,66.953021,25.665325
32,FF,2023-03-08 18:20:00,2023-03-08 19:10:00,"(1100, 1150)","(362.5892, 408.05)","(943.3087, 355.7375)",111.170134,42.615218,61.46203,23.560445,56.279022,21.573625,56.279022,21.573625,111.170134,42.615218
8,H,2023-03-08 18:25:00,2023-03-08 19:15:00,"(1105, 1155)","(153.4537, 394.5352)","(222.3449, 613.5783)",129.057918,49.472202,61.46203,23.560445,112.452642,43.106846,22.163434,8.495983,178.013028,68.238327

Step7-5. (동승자 지불 금액의 합-택시 지불 금액)/택시 지불 금액 > 0.1 이어야 5% 할인을 보장할 수 있다.

Step8. 최소최대 소요시간 증가 비율에 해당하는 ID(1순위동승예약자)와 최종 매칭을 진행한다

In [28]:
sort_last = []
ratio_index = {}
df2 = df1.copy()
len_df2 = len(df2)

for _ in range(len_df2):
  for index, row in df2.iterrows():
    i_org = df2.loc[index,'원래시간(분)']
    i_rou = df2.loc[index,'경유시간(분)']
    a_org = df2.loc[index,'타깃원래시간(분)']
    a_rou = df2.loc[index,'타깃경유시간(분)']
    sort_last.append(max((i_rou-i_org)/i_org,(a_rou-a_org)/a_org))
    ratio_index[max((i_rou-i_org)/i_org,(a_rou-a_org)/a_org)] = index

    target_user = df2.loc[ratio_index[min(sort_last)]]['ID']
    target_index = ratio_index[min(sort_last)]

    a_ind_pred = int(4800 + (df2.loc[target_index,'타깃원래거리(km)']-1.6)*100/1.31 + (df2.loc[target_index,'타깃원래시간(분)']-96/23)*200)
    i_ind_pred = int(4800 + (df2.loc[target_index,'원래거리(km)']-1.6)*100/1.31 + (df2.loc[target_index,'원래시간(분)']-96/23)*200)
    driver_rou_pred = int(4800 + (df2.loc[target_index,'총경유거리(km)']-1.6)*100/1.31 + (df2.loc[target_index,'총이동시간(분)']-96/23)*200)

    if (a_ind_pred + i_ind_pred - driver_rou_pred)/driver_rou_pred > 0.25:
      print(f"최종적으로 'A'와 '{target_user}'을(를) 매칭해준다. (비율: {(a_ind_pred + i_ind_pred - driver_rou_pred)/driver_rou_pred:.2f})")
      break
    else:
      df2 = df2.drop(index, axis=0)
      print(f"{target_user}, 비율: {(a_ind_pred + i_ind_pred - driver_rou_pred)/driver_rou_pred:.2f} => 최종 매칭 X")
  if (a_ind_pred + i_ind_pred - driver_rou_pred)/driver_rou_pred > 0.2:
    break

EE, 비율: -0.07 => 최종 매칭 X

KeyError: 31

In [14]:
'''
기본요금 1.6km 까지 4800원
131m 당 100원
30초당 100원
'''
target_index = ratio_index[min(sort_last)]
print(target_index)
df1.loc[target_index]

45

ID                              SS
출발희망시각         2023-03-08 18:35:00
최대대기시각         2023-03-08 19:25:00
시간범위                  (1115, 1165)
출발위치          (332.6486, 932.8508)
도착위치          (362.0472, 389.9234)
타깃경유시간(분)                91.200517
타깃경유거리(km)               34.960198
타깃원래시간(분)                91.128058
타깃원래거리(km)               34.932422
경유시간(분)                  82.126504
경유거리(km)                 31.481827
원래시간(분)                  52.481066
원래거리(km)                 20.117742
총이동시간(분)                115.844222
총경유거리(km)                44.406952
Name: 45, dtype: object

# Settlement Algorithm

In [15]:
a_ind_pred = int(4800 + (df1.loc[target_index,'타깃원래거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'타깃원래시간(분)']-96/23)*200)
i_ind_pred = int(4800 + (df1.loc[target_index,'원래거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'원래시간(분)']-96/23)*200)
driver_rou_pred = int(4800 + (df1.loc[target_index,'총경유거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'총이동시간(분)']-96/23)*200)

print(a_ind_pred, i_ind_pred, driver_rou_pred)

24735 15874 30401

In [16]:
a_ind_pred = int(4800 + (df1.loc[target_index,'타깃원래거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'타깃원래시간(분)']-96/23)*200)
i_ind_pred = int(4800 + (df1.loc[target_index,'원래거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'원래시간(분)']-96/23)*200)
driver_rou_pred = int(4800 + (df1.loc[target_index,'총경유거리(km)']-1.6)*100/1.31 + (df1.loc[target_index,'총이동시간(분)']-96/23)*200)

print(a_ind_pred, i_ind_pred, driver_rou_pred)

alpha = 0.5 # 동승객 최소 할인율
beta = 0.5 # 동승객 추가 할인율
gamma = 0.03 # 혹시 최소 수익률
eplison = 0.02 # 실제 요금/예상요금 비율

lower_bound = 0.2 # 알파베타 비율 최소 상한선
upper_bound = 0.5 # 알파베타 비율 최대 상한선

addia = 0.001
addib = 0.01

# 최초의 상태
a_beta = beta*((a_rou-a_org)/a_org)
a_payment = int((1-(alpha+a_beta))*a_ind_pred)

i_beta = beta*((i_rou-i_org)/i_org)
i_payment = int((1-(alpha+i_beta))*i_ind_pred)

print(f'최적화 전 이익: {a_payment + i_payment - driver_rou_pred*(1+gamma):.0f}원')
print()

# 만약 목적식이 < 0 이라면 >0가 된 순간 끝
if a_payment + i_payment - driver_rou_pred*(1+gamma) <0:
  while(True):
    a_rou, a_org = df1.loc[target_index,'타깃경유시간(분)'], df1.loc[target_index,'타깃원래시간(분)']
    i_rou, i_org = df1.loc[target_index,'경유시간(분)'], df1.loc[target_index,'원래시간(분)']

    a_beta = beta*((a_rou-a_org)/a_org)
    a_payment = int((1-(alpha+a_beta))*a_ind_pred)

    i_beta = beta*((i_rou-i_org)/i_org)
    i_payment = int((1-(alpha+i_beta))*i_ind_pred)

    ## 알파베타 비율이 정산범위 내
    if max(a_beta/alpha,i_beta/alpha)>=lower_bound and min(a_beta/alpha,i_beta/alpha)<=upper_bound:
      # alpha, beta 감소
      beta -= addib

      # alpha 감소
      if alpha>0.05:
        alpha -= addia
      else: alpha = alpha
    
    ## 알파베타 비율이 정산범위 보다 작을 때
    elif max(a_beta/alpha,i_beta/alpha)<=lower_bound:
      # alpha감소 & beta 증가
      alpha -= addia
      beta += addib

    ## 알파베타 비율이 정산범위 보다 클 때
    elif max(a_beta/alpha,i_beta/alpha)>=lower_bound:
      # alpha증가 & beta 감소
      alpha += addia
      beta -= addib


    if a_payment + i_payment - driver_rou_pred*(1+gamma)>0:
      print("type1")
      break


# 만약 목적식이 > 0 이라면 <0가 된 순간 전단계 되돌린 후 끝
else:
  while(True):
    a_rou, a_org = df1.loc[target_index,'타깃경유시간(분)'], df1.loc[target_index,'타깃원래시간(분)']
    i_rou, i_org = df1.loc[target_index,'경유시간(분)'], df1.loc[target_index,'원래시간(분)']

    a_beta = beta*((a_rou-a_org)/a_org)
    a_payment = int((1-(alpha+a_beta))*a_ind_pred)

    i_beta = beta*((i_rou-i_org)/i_org)
    i_payment = int((1-(alpha+i_beta))*i_ind_pred)

    ## 알파베타 비율이 정산범위 내
    if max(a_beta/alpha,i_beta/alpha)>=lower_bound and max(a_beta/alpha,i_beta/alpha)<=upper_bound:
      # alpha, beta 감소
      beta -= addib

      # alpha 감소
      if alpha>0.05:
        alpha -= addia
      else: alpha = alpha
    
    ## 알파베타 비율이 정산범위 보다 작을 때
    elif max(a_beta/alpha,i_beta/alpha)<=lower_bound:
      # alpha감소 & beta 증가
      alpha -= addia
      # beta += addib

    ## 알파베타 비율이 정산범위 보다 클 때
    elif max(a_beta/alpha,i_beta/alpha)>=upper_bound:
      # alpha증가 & beta 감소
      alpha += addia
      # beta -= addib

    # 전단계 롤백
    if a_payment + i_payment - driver_rou_pred*(1+gamma)<0:
      if alpha>0.05:
        alpha += addia
      else:
        alpha = alpha

      beta += addib
      a_beta = beta*((a_rou-a_org)/a_org)
      a_payment = int((1-(alpha+a_beta))*a_ind_pred)

      i_beta = beta*((i_rou-i_org)/i_org)
      i_payment = int((1-(alpha+i_beta))*i_ind_pred)
      if a_payment + i_payment - driver_rou_pred*(1+gamma)>0:
        print("type2")
        break
  


print(f'alpha: {alpha:.2f}, beta: {beta:.2f}')
print(f'타깃동승자 ratio: {a_beta/alpha:.2f} / 동승자 ratio: {i_beta/alpha:.2f}')

hoxi_profit_per_matching = round(a_payment + i_payment - (1+eplison)*driver_rou_pred)
print()
print(f'타깃동승자   {alpha*100:.2f}+{a_beta*100:.2f} => {(alpha+a_beta)*100:.2f}% 할인')
print(f'동승자       {alpha*100:.2f}+{i_beta*100:.2f}  => {(alpha+i_beta)*100:.2f}% 할인')
print(f'타깃깃동승자 {a_ind_pred}원 >> {a_payment}원')
print(f'동승자       {i_ind_pred}원 >> {i_payment}원')
print(f'혹시가 얻는 최종 이익 >> {hoxi_profit_per_matching} 원')
print()
print(f'최적화 후 이익: {a_payment + i_payment - driver_rou_pred*(1+gamma):.0f}원')

24735 15874 30401
최적화 전 이익: -15503원

type1
alpha: 0.21, beta: 0.08
타깃동승자 ratio: 0.00 / 동승자 ratio: 0.19

타깃동승자   21.20+0.01 => 21.21% 할인
동승자       21.20+3.95  => 25.15% 할인
타깃깃동승자 24735원 >> 19465원
동승자       15874원 >> 11865원
혹시가 얻는 최종 이익 >> 321 원

최적화 후 이익: 17원